spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boda?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
  static-path-pattern: ../resources/static/**

  compile group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1'
server:
  port: 8080